name: Deploy to Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -la
          cp -r "${{ github.workspace }}/个人项目合集" "${{ github.workspace }}/website/"
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: website
      - name: Deploy
        uses: actions/deploy-pages@v4